### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/license-reporter#163]
```
[hf@localhost project-foo]$ license-reporter 
/home/hf/d/license-reporter/lib/file-reader.js:18
  if (url.startsWith('http')) {
         ^

TypeError: Cannot read property 'startsWith' of undefined
    at Object.readAsJson (/home/hf/d/license-reporter/lib/file-reader.js:18:10)
```

tested on a local "foo" project.

**Comment by helio-frota** [comment]
I saw this before this seems to have relation with #159 : /

**Comment by helio-frota** [comment]
now the output is: 
```
[hf@localhost project-foo]$ license-reporter 
Apache License 2.0
/home/hf/d/license-reporter/lib/unified-list.js:119
  if (unifiedList[name]) {
                  ^

TypeError: Cannot read property 'Apache License 2.0' of undefined
    at _urlForName (/home/hf/d/license-reporter/lib/unified-list.js:119:19)
    at Object.urlForName (/home/hf/d/license-reporter/lib/unified-list.js:111:10)
    at entry (/home/hf/d/license-reporter/bin/cli.js:31:27)
    at addLicenseEntry (/home/hf/d/license-reporter/bin/cli.js:54:45)
    at xmlObjectData (/home/hf/d/license-reporter/bin/cli.js:107:9)
    at checker.init (/home/hf/d/license-reporter/bin/cli.js:139:17)
    at /home/hf/d/license-reporter/node_modules/license-checker/lib/index.js:373:9
    at /home/hf/d/license-reporter/node_modules/read-installed/read-installed.js:142:5
    at /home/hf/d/license-reporter/node_modules/read-installed/read-installed.js:263:14
    at cb (/home/hf/d/license-reporter/node_modules/slide/lib/async-map.js:47:24)
```
