### ISSUE TITLE
minor bug after refactor

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/license-reporter#247]
```console
hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/genet (master)
$ license-reporter console
module.js:538
    throw err;
    ^

Error: Cannot find module '../utils/save.mdl'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\hf\Desktop\dev\license-reporter\lib\commands\save.cmd.js:9:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/license-reporter/commit/0c54d331d3e2eb77bbd8f8c1d8332ef91005d4eb
