### ISSUE TITLE
when using merge command, the tool should to create 'licenses' directory on the CWD directory before merge

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/license-reporter#249]
to avoid:

```
{ Error: ENOENT: no such file or directory, open '/home/hf/Desktop/mea5n-booster/licenses/merged.xml'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at xml.merge.then.result (/home/hf/Desktop/license-reporter/lib/modules/merge.mdl.js:21:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/hf/Desktop/mea5n-booster/licenses/merged.xml' }
```

**Comment by helio-frota** [comment]
I dunno if it is a bug, since the usual way to use a merge command in the past is inside a project directory with `node_modules`folder.

**Comment by helio-frota** [comment]
After use this on a project like mea5n-booster, for me it looks like a bug...

``` 
.
├── backend
│   ├── licenses
│   ├── model
│   ├── node_modules
│   ├── package.json
│   ├── package-lock.json
│   ├── server.js
│   └── test
├── frontend
│   ├── e2e
│   ├── karma.conf.js
│   ├── licenses
│   ├── node_modules
│   ├── package.json
│   ├── package-lock.json
│   ├── protractor.conf.js
│   ├── src
│   ├── tsconfig.json
│   └── tslint.json
├── LICENSE
├── licenses
│   └── frontend_and_backend.xml
└── README.md
---------> We have no package.json here on root directory <------
```
